package(default_visibility = ["//visibility:public"])

cc_library(
    name = "qp_solver",
    srcs = ["qp_solver.cc"],
    hdrs = ["qp_solver.h"],
    strip_include_prefix = "/src",
    deps = [
        "@eigen",
    ],
)
